### ISSUE TITLE
FFTW issue

### ISSUE THREAD

**Issue by Bryce-Cannon** [PyDL/pyflct#1]
I am a beginner, and I'm having trouble installing pyflct. I previously had an issue that was solved by installing C++ Build Tools. Now I'm getting an error where the file fftw3.h cannot be found. Here is the full output. I'm using anaconda. Please advise. 

C:\Users\cbryc>pip install pyflct
Collecting pyflct
  Using cached pyflct-0.2.1.tar.gz (737 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy in c:\users\cbryc\anaconda3\lib\site-packages (from pyflct) (1.18.5)
Building wheels for collected packages: pyflct
  Building wheel for pyflct (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\cbryc\anaconda3\python.exe' 'c:\users\cbryc\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\cbryc\AppData\Local\Temp\tmp7omtsubs'
       cwd: C:\Users\cbryc\AppData\Local\Temp\pip-install-dfpcx9ey\pyflct_4b155df4e81a47ab8ccb42f0950de13b
  Complete output (60 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\pyflct
  copying pyflct\flct.py -> build\lib.win-amd64-3.8\pyflct
  copying pyflct\setup_package.py -> build\lib.win-amd64-3.8\pyflct
  copying pyflct\utils.py -> build\lib.win-amd64-3.8\pyflct
  copying pyflct\version.py -> build\lib.win-amd64-3.8\pyflct
  copying pyflct\__init__.py -> build\lib.win-amd64-3.8\pyflct
  creating build\lib.win-amd64-3.8\pyflct\data
  copying pyflct\data\__init__.py -> build\lib.win-amd64-3.8\pyflct\data
  creating build\lib.win-amd64-3.8\pyflct\tests
  copying pyflct\tests\test_flct.py -> build\lib.win-amd64-3.8\pyflct\tests
  copying pyflct\tests\test_utils.py -> build\lib.win-amd64-3.8\pyflct\tests
  copying pyflct\tests\__init__.py -> build\lib.win-amd64-3.8\pyflct\tests
  creating build\lib.win-amd64-3.8\pyflct\data\test
  copying pyflct\data\test\__init__.py -> build\lib.win-amd64-3.8\pyflct\data\test
  running egg_info
  writing pyflct.egg-info\PKG-INFO
  writing dependency_links to pyflct.egg-info\dependency_links.txt
  writing requirements to pyflct.egg-info\requires.txt
  writing top-level names to pyflct.egg-info\top_level.txt
  reading manifest file 'pyflct.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'CHANGES.rst'
  warning: no files found matching '*.pxd' under directory 'pyflct'
  no previously-included directories found matching 'build'
  no previously-included directories found matching 'docs\_build'
  no previously-included directories found matching 'docs\api'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.o' found anywhere in distribution
  warning: no previously-included files matching '_flct*' found anywhere in distribution
  warning: no previously-included files matching 'flct.c' found anywhere in distribution
  warning: no previously-included files matching 'compiler_version*' found anywhere in distribution
  writing manifest file 'pyflct.egg-info\SOURCES.txt'
  copying pyflct\flct.pyx -> build\lib.win-amd64-3.8\pyflct
  copying pyflct\sunkit.c -> build\lib.win-amd64-3.8\pyflct
  copying pyflct\sunkit.h -> build\lib.win-amd64-3.8\pyflct
  copying pyflct\data\README.rst -> build\lib.win-amd64-3.8\pyflct\data
  copying pyflct\data\test\IDL.txt -> build\lib.win-amd64-3.8\pyflct\data\test
  copying pyflct\data\test\hashgauss.dat -> build\lib.win-amd64-3.8\pyflct\data\test
  copying pyflct\data\test\hashgauss_F1.csv -> build\lib.win-amd64-3.8\pyflct\data\test
  copying pyflct\data\test\hashgauss_F2.csv -> build\lib.win-amd64-3.8\pyflct\data\test
  copying pyflct\data\test\testgauss_vm.csv -> build\lib.win-amd64-3.8\pyflct\data\test
  copying pyflct\data\test\testgauss_vx.csv -> build\lib.win-amd64-3.8\pyflct\data\test
  copying pyflct\data\test\testgauss_vy.csv -> build\lib.win-amd64-3.8\pyflct\data\test
  copying pyflct\data\test\testgaussvel.dat -> build\lib.win-amd64-3.8\pyflct\data\test
  running build_ext
  cythoning .\pyflct\flct.pyx to .\pyflct\flct.c
  building 'pyflct._flct' extension
  creating build\temp.win-amd64-3.8
  creating build\temp.win-amd64-3.8\Release
  creating build\temp.win-amd64-3.8\Release\cextern
  creating build\temp.win-amd64-3.8\Release\pyflct
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\cbryc\AppData\Local\Temp\pip-build-env-zqkn36ye\overlay\Lib\site-packages\numpy\core\include -Ic:\users\cbryc\anaconda3\include -Icextern -Ic:\users\cbryc\anaconda3\Library\include -Ic:\users\cbryc\anaconda3\include -Ic:\users\cbryc\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tccextern\flctsubs.c /Fobuild\temp.win-amd64-3.8\Release\cextern\flctsubs.obj
  flctsubs.c
  cextern\flctsubs.h(45): fatal error C1083: Cannot open include file: 'fftw3.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pyflct
Failed to build pyflct
ERROR: Could not build wheels for pyflct which use PEP 517 and cannot be installed directly

**Comment by PyDL** [comment]
Sorry, though with the same name, pyflct in pip was not developed by me - so not relevant to this repository.
